apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: power-cmk-pod-inference
  name: power-cmk-pod-inference
spec:
  selector:
   matchLabels:
    app: power-cmk-pod-inference
  replicas: 0
  template:
    metadata:
      labels:
        app: power-cmk-pod-inference
    spec:
     containers:
      - name: power-cmk-pod-inference-container
        image: hrabhijith/lane-detection:normal
        ports:
         - containerPort: 5005
           hostPort: 5005
        resources:
         requests:
          memory: "500Mi"
          cpu: "1"
          power.intel.com/performance: "1"
         limits:
          memory: "500Mi"
          cpu: "1"
          power.intel.com/performance: "1"
        volumeMounts:
         - name: tmp
           mountPath: "/tmp"
        imagePullPolicy: Always
        securityContext:
         allowPrivilegeEscalation: true
         readOnlyRootFilesystem: true
         runAsNonRoot: false
         privileged: true
         capabilities:
          drop:
           - all
     volumes:
      - hostPath:
         path: "/tmp"
        name: tmp
     nodeSelector:
      kubernetes.io/hostname: "nuc"
